- name: "foo"
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    gcp_project: ENTER_PROJECT_NAME_HERE
    gcp_cred_kind: serviceaccount
    gcp_cred_file: ENTER_JSON_FILE_PATH_AND_NAME_HERE

  tasks:
    - name: create a disk
      google.cloud.gcp_compute_disk:
          name: foo-disk-instance
          size_gb: 50
          source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
          zone: us-central1-a
          project: "{{ gcp_project }}"
          auth_kind: "{{ gcp_cred_kind }}"
          service_account_file: "{{ gcp_cred_file }}"
          state: present
      register: disk

    - name: create a network
      google.cloud.gcp_compute_network:
          name: foo-network-instance
          project: "{{ gcp_project }}"
          auth_kind: "{{ gcp_cred_kind }}"
          service_account_file: "{{ gcp_cred_file }}"
          auto_create_subnetworks: yes
          state: present
      register: network

    - name: create a address
      google.cloud.gcp_compute_address:
          name: foo-address-instance
          region: us-central1
          project: "{{ gcp_project }}"
          auth_kind: "{{ gcp_cred_kind }}"
          service_account_file: "{{ gcp_cred_file }}"
          state: present
      register: address

    - name: create a instance
      google.cloud.gcp_compute_instance:
          name: foo-instance
          machine_type: n1-standard-1
          disks:
          - auto_delete: 'true'
            boot: 'true'
            source: "{{ disk }}"
          - auto_delete: 'true'
            interface: NVME
            type: SCRATCH
            initialize_params:
              disk_type: local-ssd
          metadata:
            startup-script-url: gs:://graphite-playground/bootstrap.sh
            cost-center: '12345'
          labels:
            environment: sandbox
          network_interfaces:
          - network: "{{ network }}"
            access_configs:
            - name: External NAT
              nat_ip: "{{ address }}"
              type: ONE_TO_ONE_NAT
          zone: us-central1-a
          project: "{{ gcp_project }}"
          auth_kind: "{{ gcp_cred_kind }}"
          service_account_file: "{{ gcp_cred_file }}"
          state: present
